### ISSUE TITLE
Import problematic csv-file

### ISSUE THREAD

**Issue by antpn** [Greensway/shinyBIRDS#21]
[This file](https://greenswayab-my.sharepoint.com/:x:/g/personal/anton_greensway_se/EcKZSo4JO_BPnXarOh2TV84BJps_UQKC5q-t9I3pP5CHow?e=4QHF44) seems to break the import. 

It's encoded in 8859-1 (LATIN1), seperated with semicolon and quoted with double quotation. 

Note that since you can’t share a csv-file in Onedrive without Microsoft interpreting it as an Excel, I’ve saved it as an .scsv (semicolon separated values).

**Comment by Greensway** [comment]
kanske för att den är .Scsv?

**Comment by Greensway** [comment]
no, it breaks it anyway....

**Comment by aleruete** [comment]
it crashes without message.. 😟

**Comment by aleruete** [comment]
it has to do with the semicolon... now exactly sure how. I manage to open the file it previously stated the ;

**Comment by antpn** [comment]
Strange... The exact same file has worked in previous versions. 

Don’t know if it is so but maybe there could be semicolons in some cell values and that there is a problem with how the quoting is interpreted? Just a theory…

**Comment by aleruete** [comment]
now it works.. ;)
