### ISSUE TITLE
Explore visits crash

### ISSUE THREAD

**Issue by antpn** [Greensway/shinyBIRDS#22]
The program crashes for me when trying to “Explore visits” with observations from [this file](https://greenswayab-my.sharepoint.com/:u:/g/personal/anton_greensway_se/EQg-4XmFEStPkBFkjsn1CYQBbEe_R6S_XwOaY-DhwOvXsg?e=JURqeU).

I’m starting the program, going directly to “Load PBD”, importing the file, stepping through “Define visits” and “Organise”, keeping every setting as default. When pressing “Explore visits” I get disconnected from the server. 

Note that since you can’t share a csv-file in Onedrive without Microsoft interpreting it as an Excel, I’ve saved it as an .tsv (tab separated values).

**Comment by aleruete** [comment]
weird, I cant reproduce local but I see in shinyapps that there is a problem with identicalCRS. Maybe related to rgdal and sp version in the server
@antpn is it supposed to .Tcv?

**Comment by antpn** [comment]
The file is a .tsv (tab separated values). When downloaded you can rename it to whatever you like (e.g. .csv, .txt). That should not matter, and I don't think it affects the program. 

When I tested it, the file was a .csv (nothing else changed) but since Microsoft is stupid and you cannot share .csv over OneDrive without Microsoft interpreting it as an Excel I had to change the file type.
